/*
db.laminarefs.insertMany([
    { equipo: 'Especiales', nombre: 'FWC 0', imgUrl: 'link', numero: 0, tipo: 'especial'},
    { equipo: 'Especiales', nombre: 'FWC 1', imgUrl: 'link', numero: 1, tipo: 'especial'},
    { equipo: 'Especiales', nombre: 'FWC 2', imgUrl: 'link', numero: 2, tipo: 'especial'},
    { equipo: 'Especiales', nombre: 'FWC 3', imgUrl: 'link', numero: 3, tipo: 'especial'},
    { equipo: 'Especiales', nombre: 'FWC 4', imgUrl: 'link', numero: 4, tipo: 'especial'},
    { equipo: 'Especiales', nombre: 'FWC 5', imgUrl: 'link', numero: 5, tipo: 'especial'},
    { equipo: 'Especiales', nombre: 'FWC 6', imgUrl: 'link', numero: 6, tipo: 'especial'},
    { equipo: 'Especiales', nombre: 'FWC 7', imgUrl: 'link', numero: 7, tipo: 'especial'},
    { equipo: 'Especiales', nombre: 'FWC 8', imgUrl: 'link', numero: 8, tipo: 'especial'},
    { equipo: 'Qatar', nombre: 'Escudo de Qatar', imgUrl: 'link', numero: 9, tipo: 'escudo'},
    { equipo: 'Qatar', nombre: 'SAAD AL SHEEB', imgUrl: 'link', numero: 10, tipo: 'jugador'},
    { equipo: 'Qatar', nombre: 'BASSAM ALRAWI', imgUrl: 'link', numero: 11, tipo: 'jugador'},
    { equipo: 'Qatar', nombre: 'ABDULKARIM HASSAN', imgUrl: 'link', numero: 12, tipo: 'jugador'},
    { equipo: 'Qatar', nombre: 'BOUALEM KHOUHI', imgUrl: 'link', numero: 13, tipo: 'jugador'},
    { equipo: 'Qatar', nombre: 'PEDRO MIGUEL', imgUrl: 'link', numero: 14, tipo: 'jugador'},
    { equipo: 'Qatar', nombre: 'TAREK SALMAN', imgUrl: 'link', numero: 15, tipo: 'jugador'},
    { equipo: 'Qatar', nombre: 'KARIM BOUDIAF', imgUrl: 'link', numero: 16, tipo: 'jugador'},
    { equipo: 'Qatar', nombre: 'ABDULAZIZ HATEM', imgUrl: 'link', numero: 17, tipo: 'jugador'},
    { equipo: 'Qatar', nombre: 'ASKRAM HASSAN', imgUrl: 'link', numero: 18, tipo: 'jugador'},
    { equipo: 'Qatar', nombre: 'HASAN AL-HAYDOS', imgUrl: 'link', numero: 19, tipo: 'jugador'},
    { equipo: 'Qatar', nombre: 'ALMOEZ ALI', imgUrl: 'link', numero: 20, tipo: 'jugador'},
    { equipo: 'Ecuador', nombre: 'Escudo de Ecuador', imgUrl: 'link', numero: 21, tipo: 'escudo'},
    { equipo: 'Ecuador', nombre: 'HERNÁN GALINDEZ', imgUrl: 'link', numero: 22, tipo: 'jugador'},
    { equipo: 'Ecuador', nombre: 'PERVIS ESTUPIÑAN', imgUrl: 'link', numero: 23, tipo: 'jugador'},
    { equipo: 'Ecuador', nombre: 'PIERO HINCAPIE', imgUrl: 'link', numero: 24, tipo: 'jugador'},
    { equipo: 'Ecuador', nombre: 'ANGELO PRECIADO', imgUrl: 'link', numero: 25, tipo: 'jugador'},
    { equipo: 'Ecuador', nombre: 'FÉLIX TORRES', imgUrl: 'link', numero: 26, tipo: 'jugador'},
    { equipo: 'Ecuador', nombre: 'MOISES CAICEDO', imgUrl: 'link', numero: 27, tipo: 'jugador'},
    { equipo: 'Ecuador', nombre: 'CARLOS GRUESO', imgUrl: 'link', numero: 28, tipo: 'jugador'},
    { equipo: 'Ecuador', nombre: 'MICHAEL ESTRADA', imgUrl: 'link', numero: 29, tipo: 'jugador'},
    { equipo: 'Ecuador', nombre: 'ÁNGEL MENA', imgUrl: 'link', numero: 30, tipo: 'jugador'},
    { equipo: 'Ecuador', nombre: 'GONZALO PLATA', imgUrl: 'link', numero: 31, tipo: 'jugador'},
    { equipo: 'Ecuador', nombre: 'ENNER VALENCIA', imgUrl: 'link', numero: 32, tipo: 'jugador'},
    { equipo: 'Senegal', nombre: 'Escudo de Senegal', imgUrl: 'link', numero: 33, tipo: 'escudo'},
    { equipo: 'Senegal', nombre: 'MENDY', imgUrl: 'link', numero: 34, tipo: 'jugador'},
    { equipo: 'Senegal', nombre: 'CISS', imgUrl: 'link', numero: 36, tipo: 'jugador'},
    { equipo: 'Senegal', nombre: 'DIALLO', imgUrl: 'link', numero: 37, tipo: 'jugador'},
    { equipo: 'Senegal', nombre: 'KOULIBANY', imgUrl: 'link', numero: 38, tipo: 'jugador'},
    { equipo: 'Senegal', nombre: 'SARR', imgUrl: 'link', numero: 39, tipo: 'jugador'},
    { equipo: 'Senegal', nombre: 'GUEYE', imgUrl: 'link', numero: 40, tipo: 'jugador'},
    { equipo: 'Senegal', nombre: 'KOUYATE', imgUrl: 'link', numero: 41, tipo: 'jugador'},
    { equipo: 'Senegal', nombre: 'NAMPALYS MENDY', imgUrl: 'link', numero: 42, tipo: 'jugador'},
    { equipo: 'Senegal', nombre: 'DIA', imgUrl: 'link', numero: 43, tipo: 'jugador'},
    { equipo: 'Senegal', nombre: 'MANÉ', imgUrl: 'link', numero: 44, tipo: 'jugador'},
    { equipo: 'Senegal', nombre: 'ISMAILA SARR', imgUrl: 'link', numero: 45, tipo: 'jugador'},
    { equipo: 'Paises bajos', nombre: 'Escudo de Paises Bajos', imgUrl: 'link', numero: 46, tipo: 'escudo'},
    { equipo: 'Paises bajos', nombre: 'BILJOW', imgUrl: 'link', numero: 47, tipo: 'jugador'},
    { equipo: 'Paises bajos', nombre: 'BLIND', imgUrl: 'link', numero: 48, tipo: 'jugador'},
    { equipo: 'Paises bajos', nombre: 'DE LIGT', imgUrl: 'link', numero: 49, tipo: 'jugador'},
    { equipo: 'Paises bajos', nombre: 'DE VRIJ', imgUrl: 'link', numero: 50, tipo: 'jugador'},
    { equipo: 'Paises bajos', nombre: 'DUMFRIES', imgUrl: 'link', numero: 51, tipo: 'jugador'},
    { equipo: 'Paises bajos', nombre: 'VAN DIJK', imgUrl: 'link', numero: 52, tipo: 'jugador'},
    { equipo: 'Paises bajos', nombre: 'DE JONG', imgUrl: 'link', numero: 53, tipo: 'jugador'},
    { equipo: 'Paises bajos', nombre: 'KLAASSEN', imgUrl: 'link', numero: 54, tipo: 'jugador'},
    { equipo: 'Paises bajos', nombre: 'WIJNALDUM', imgUrl: 'link', numero: 55, tipo: 'jugador'},
    { equipo: 'Paises bajos', nombre: 'BERGWIJN', imgUrl: 'link', numero: 56, tipo: 'jugador'},
    { equipo: 'Paises bajos', nombre: 'DEPAY', imgUrl: 'link', numero: 57, tipo: 'jugador'},
    { equipo: 'Inglaterra', nombre: 'Escudo de Inglaterra', imgUrl: 'link', numero: 58, tipo: 'escudo'},
    { equipo: 'Inglaterra', nombre: 'PICKFORD', imgUrl: 'link', numero: 59, tipo: 'jugador'},
    { equipo: 'Inglaterra', nombre: 'MAGUIRE', imgUrl: 'link', numero: 60, tipo: 'jugador'},
    { equipo: 'Inglaterra', nombre: 'SHAW', imgUrl: 'link', numero: 61, tipo: 'jugador'},
    { equipo: 'Inglaterra', nombre: 'STONES', imgUrl: 'link', numero: 62, tipo: 'jugador'},
    { equipo: 'Inglaterra', nombre: 'WALKER', imgUrl: 'link', numero: 63, tipo: 'jugador'},
    { equipo: 'Inglaterra', nombre: 'MOUNT', imgUrl: 'link', numero: 64, tipo: 'jugador'},
    { equipo: 'Inglaterra', nombre: 'PHILLIPS', imgUrl: 'link', numero: 65, tipo: 'jugador'},
    { equipo: 'Inglaterra', nombre: 'RICE', imgUrl: 'link', numero: 66, tipo: 'jugador'},
    { equipo: 'Inglaterra', nombre: 'FODEN', imgUrl: 'link', numero: 67, tipo: 'jugador'},
    { equipo: 'Inglaterra', nombre: 'KANE', imgUrl: 'link', numero: 68, tipo: 'jugador'},
    { equipo: 'Inglaterra', nombre: 'STERLING', imgUrl: 'link', numero: 69, tipo: 'jugador'},
    { equipo: 'Iran', nombre: 'Escudo de Iran', imgUrl: 'link', numero: 70, tipo: 'escudo'},
    { equipo: 'Iran', nombre: 'BEIRANVAND', imgUrl: 'link', numero: 71, tipo: 'jugador'},
    { equipo: 'Iran', nombre: 'KANAANI', imgUrl: 'link', numero: 72, tipo: 'jugador'},
    { equipo: 'Iran', nombre: 'KHALILZADEH', imgUrl: 'link', numero: 73, tipo: 'jugador'},
    { equipo: 'Iran', nombre: 'MOHAMMADI', imgUrl: 'link', numero: 74, tipo: 'jugador'},
    { equipo: 'Iran', nombre: 'NOORAFKAN', imgUrl: 'link', numero: 75, tipo: 'jugador'},
    { equipo: 'Iran', nombre: 'EZATOLAHI', imgUrl: 'link', numero: 76, tipo: 'jugador'},
    { equipo: 'Iran', nombre: 'GHOLIZADEH', imgUrl: 'link', numero: 77, tipo: 'jugador'},
    { equipo: 'Iran', nombre: 'JAHANBAKHSH', imgUrl: 'link', numero: 78, tipo: 'jugador'},
    { equipo: 'Iran', nombre: 'NOUROLLAHI', imgUrl: 'link', numero: 79, tipo: 'jugador'},
    { equipo: 'Iran', nombre: 'AZMOUN', imgUrl: 'link', numero: 80, tipo: 'jugador'},
    { equipo: 'Iran', nombre: 'TAREMI', imgUrl: 'link', numero: 81, tipo: 'jugador'},
    { equipo: 'Estados Unidos', nombre: 'Escudo de Estados Unidos', imgUrl: 'link', numero: 82, tipo: 'escudo'},
    { equipo: 'Estados Unidos', nombre: 'TURNER', imgUrl: 'link', numero: 83, tipo: 'jugador'},
    { equipo: 'Estados Unidos', nombre: 'DEST', imgUrl: 'link', numero: 84, tipo: 'jugador'},
    { equipo: 'Estados Unidos', nombre: 'ROBINSON', imgUrl: 'link', numero: 86, tipo: 'jugador'},
    { equipo: 'Estados Unidos', nombre: 'YEDLIN', imgUrl: 'link', numero: 87, tipo: 'jugador'},
    { equipo: 'Estados Unidos', nombre: 'ZIMMERMAN', imgUrl: 'link', numero: 88, tipo: 'jugador'},
    { equipo: 'Estados Unidos', nombre: 'ADAMS', imgUrl: 'link', numero: 89, tipo: 'jugador'},
    { equipo: 'Estados Unidos', nombre: 'MCKENNIE', imgUrl: 'link', numero: 90, tipo: 'jugador'},
    { equipo: 'Estados Unidos', nombre: 'PEPI', imgUrl: 'link', numero: 91, tipo: 'jugador'},
    { equipo: 'Estados Unidos', nombre: 'PULISIC', imgUrl: 'link', numero: 92, tipo: 'jugador'},
    { equipo: 'Estados Unidos', nombre: 'REYNA', imgUrl: 'link', numero: 93, tipo: 'jugador'},
    { equipo: 'Estados Unidos', nombre: 'WEAH', imgUrl: 'link', numero: 94, tipo: 'jugador'},
    { equipo: 'Gales', nombre: 'Escudo de Gales', imgUrl: 'link', numero: 95, tipo: 'escudo'},
    { equipo: 'Gales', nombre: 'HENNESSEY', imgUrl: 'link', numero: 96, tipo: 'jugador'},
    { equipo: 'Gales', nombre: 'AMPADU', imgUrl: 'link', numero: 97, tipo: 'jugador'},
    { equipo: 'Gales', nombre: 'DAVIES', imgUrl: 'link', numero: 98, tipo: 'jugador'},
    { equipo: 'Gales', nombre: 'ROBERTS', imgUrl: 'link', numero: 99, tipo: 'jugador'},
    { equipo: 'Gales', nombre: 'RODON', imgUrl: 'link', numero: 100, tipo: 'jugador'},
    { equipo: 'Gales', nombre: 'WILLIAMS', imgUrl: 'link', numero: 101, tipo: 'jugador'},
    { equipo: 'Gales', nombre: 'ALLEN', imgUrl: 'link', numero: 102, tipo: 'jugador'},
    { equipo: 'Gales', nombre: 'RAMSEY', imgUrl: 'link', numero: 103, tipo: 'jugador'},
    { equipo: 'Gales', nombre: 'BALE', imgUrl: 'link', numero: 104, tipo: 'jugador'},
    { equipo: 'Gales', nombre: 'JAMES', imgUrl: 'link', numero: 105, tipo: 'jugador'},
    { equipo: 'Gales', nombre: 'MOORE', imgUrl: 'link', numero: 106, tipo: 'jugador'},
    { equipo: 'Argentina', nombre: 'Escudo de Argentina', imgUrl: 'link', numero: 107, tipo: 'escudo'},
    { equipo: 'Argentina', nombre: 'MARTINEZ', imgUrl: 'link', numero: 108, tipo: 'jugador'},
    { equipo: 'Argentina', nombre: 'ACUÑA', imgUrl: 'link', numero: 109, tipo: 'jugador'},
    { equipo: 'Argentina', nombre: 'MOLINA', imgUrl: 'link', numero: 110, tipo: 'jugador'},
    { equipo: 'Argentina', nombre: 'OTAMENDI', imgUrl: 'link', numero: 111, tipo: 'jugador'},
    { equipo: 'Argentina', nombre: 'ROMERO', imgUrl: 'link', numero: 112, tipo: 'jugador'},
    { equipo: 'Argentina', nombre: 'DE PAUL', imgUrl: 'link', numero: 113, tipo: 'jugador'},
    { equipo: 'Argentina', nombre: 'DI MARIA', imgUrl: 'link', numero: 114, tipo: 'jugador'},
    { equipo: 'Argentina', nombre: 'LO CELSO', imgUrl: 'link', numero: 115, tipo: 'jugador'},
    { equipo: 'Argentina', nombre: 'PAREDES', imgUrl: 'link', numero: 116, tipo: 'jugador'},
    { equipo: 'Argentina', nombre: 'MARTINEZ', imgUrl: 'link', numero: 117, tipo: 'jugador'},
    { equipo: 'Argentina', nombre: 'MESSI', imgUrl: 'link', numero: 118, tipo: 'jugador'},
    { equipo: 'Arabia Saudi', nombre: 'Escudo de Arabia Saudi', imgUrl: 'link', numero: 119, tipo: 'escudo'},
    { equipo: 'Arabia Saudi', nombre: 'AL-AMRI', imgUrl: 'link', numero: 120, tipo: 'jugador'},
    { equipo: 'Arabia Saudi', nombre: 'AL-GHANNAM', imgUrl: 'link', numero: 121, tipo: 'jugador'},
    { equipo: 'Arabia Saudi', nombre: 'AL-SHAHRANI', imgUrl: 'link', numero: 122, tipo: 'jugador'},
    { equipo: 'Arabia Saudi', nombre: 'AL-TAMBAKTI', imgUrl: 'link', numero: 123, tipo: 'jugador'},
    { equipo: 'Arabia Saudi', nombre: 'MADU', imgUrl: 'link', numero: 124, tipo: 'jugador'},
    { equipo: 'Arabia Saudi', nombre: 'AL-FARAJ', imgUrl: 'link', numero: 125, tipo: 'jugador'},
    { equipo: 'Arabia Saudi', nombre: 'AL-MALKI', imgUrl: 'link', numero: 126, tipo: 'jugador'},
    { equipo: 'Arabia Saudi', nombre: 'KANNO', imgUrl: 'link', numero: 127, tipo: 'jugador'},
    { equipo: 'Arabia Saudi', nombre: 'AL-DAWSARI', imgUrl: 'link', numero: 128, tipo: 'jugador'},
    { equipo: 'Arabia Saudi', nombre: 'KHALID AL-GHANNAM', imgUrl: 'link', numero: 129, tipo: 'jugador'},
    { equipo: 'México', nombre: 'Escudo de México', imgUrl: 'link', numero: 130, tipo: 'escudo'},
    { equipo: 'México', nombre: 'OCHOA', imgUrl: 'link', numero: 132, tipo: 'jugador'},
    { equipo: 'México', nombre: 'ARAÚJO', imgUrl: 'link', numero: 133, tipo: 'jugador'},
    { equipo: 'México', nombre: 'GALLARDO', imgUrl: 'link', numero: 134, tipo: 'jugador'},
    { equipo: 'México', nombre: 'MONTES', imgUrl: 'link', numero: 135, tipo: 'jugador'},
    { equipo: 'México', nombre: 'SÁNCHEZ', imgUrl: 'link', numero: 136, tipo: 'jugador'},
    { equipo: 'México', nombre: 'ÁLVAREZ', imgUrl: 'link', numero: 137, tipo: 'jugador'},
    { equipo: 'México', nombre: 'CORONA', imgUrl: 'link', numero: 138, tipo: 'jugador'},
    { equipo: 'México', nombre: 'HERRERA', imgUrl: 'link', numero: 139, tipo: 'jugador'},
    { equipo: 'México', nombre: 'RODRIGUEZ', imgUrl: 'link', numero: 140, tipo: 'jugador'},
    { equipo: 'México', nombre: 'JIMENEZ', imgUrl: 'link', numero: 141, tipo: 'jugador'},
    { equipo: 'México', nombre: 'LOZANO', imgUrl: 'link', numero: 142, tipo: 'jugador'},
    { equipo: 'Polonia', nombre: 'Escudo de Polonia', imgUrl: 'link', numero: 143, tipo: 'escudo'},
    { equipo: 'Polonia', nombre: 'SZCZESNY', imgUrl: 'link', numero: 144, tipo: 'jugador'},
    { equipo: 'Polonia', nombre: 'BEDNAREK', imgUrl: 'link', numero: 145, tipo: 'jugador'},
    { equipo: 'Polonia', nombre: 'EERESZYNSKY', imgUrl: 'link', numero: 146, tipo: 'jugador'},
    { equipo: 'Polonia', nombre: 'CASH', imgUrl: 'link', numero: 147, tipo: 'jugador'},
    { equipo: 'Polonia', nombre: 'GLIK', imgUrl: 'link', numero: 148, tipo: 'jugador'},
    { equipo: 'Polonia', nombre: 'JOZWIAK', imgUrl: 'link', numero: 149, tipo: 'jugador'},
    { equipo: 'Polonia', nombre: 'KRYCHOWIAK', imgUrl: 'link', numero: 150, tipo: 'jugador'},
    { equipo: 'Polonia', nombre: 'MODER', imgUrl: 'link', numero: 151, tipo: 'jugador'},
    { equipo: 'Polonia', nombre: 'ZIELINSKI', imgUrl: 'link', numero: 152, tipo: 'jugador'},
    { equipo: 'Polonia', nombre: 'LEWANDOWSKI', imgUrl: 'link', numero: 153, tipo: 'jugador'},
    { equipo: 'Polonia', nombre: 'MILIK', imgUrl: 'link', numero: 154, tipo: 'jugador'},
    { equipo: 'Francia', nombre: 'Escudo de Francia', imgUrl: 'link', numero: 155, tipo: 'escudo'},
    { equipo: 'Francia', nombre: 'LLORIS', imgUrl: 'link', numero: 156, tipo: 'jugador'},
    { equipo: 'Francia', nombre: 'HERNANDEZ', imgUrl: 'link', numero: 157, tipo: 'jugador'},
    { equipo: 'Francia', nombre: 'KIMPEMBE', imgUrl: 'link', numero: 158, tipo: 'jugador'},
    { equipo: 'Francia', nombre: 'KOUNDE', imgUrl: 'link', numero: 159, tipo: 'jugador'},
    { equipo: 'Francia', nombre: 'VARANE', imgUrl: 'link', numero: 160, tipo: 'jugador'},
    { equipo: 'Francia', nombre: 'KANTE', imgUrl: 'link', numero: 161, tipo: 'jugador'},
    { equipo: 'Francia', nombre: 'POGBA', imgUrl: 'link', numero: 162, tipo: 'jugador'},
    { equipo: 'Francia', nombre: 'RABIOT', imgUrl: 'link', numero: 163, tipo: 'jugador'},
    { equipo: 'Francia', nombre: 'BENZEMA', imgUrl: 'link', numero: 164, tipo: 'jugador'},
    { equipo: 'Francia', nombre: 'GRIEZMANN', imgUrl: 'link', numero: 165, tipo: 'jugador'},
    { equipo: 'Francia', nombre: 'MBAPPÉ', imgUrl: 'link', numero: 166, tipo: 'jugador'},
    { equipo: 'Australia', nombre: 'Escudo de Australia', imgUrl: 'link', numero: 167, tipo: 'escudo'},
    { equipo: 'Australia', nombre: 'RYAN', imgUrl: 'link', numero: 168, tipo: 'jugador'},
    { equipo: 'Australia', nombre: 'BEHICH', imgUrl: 'link', numero: 169, tipo: 'jugador'},
    { equipo: 'Australia', nombre: 'GRANT', imgUrl: 'link', numero: 170, tipo: 'jugador'},
    { equipo: 'Australia', nombre: 'SAINSBURY', imgUrl: 'link', numero: 171, tipo: 'jugador'},
    { equipo: 'Australia', nombre: 'SOUTTAR', imgUrl: 'link', numero: 172, tipo: 'jugador'},
    { equipo: 'Australia', nombre: 'HRUSTIC', imgUrl: 'link', numero: 173, tipo: 'jugador'},
    { equipo: 'Australia', nombre: 'IRVINE', imgUrl: 'link', numero: 174, tipo: 'jugador'},
    { equipo: 'Australia', nombre: 'MOOY', imgUrl: 'link', numero: 175, tipo: 'jugador'},
    { equipo: 'Australia', nombre: 'BOYLE', imgUrl: 'link', numero: 176, tipo: 'jugador'},
    { equipo: 'Australia', nombre: 'DUKE', imgUrl: 'link', numero: 177, tipo: 'jugador'},
    { equipo: 'Australia', nombre: 'LECKIE', imgUrl: 'link', numero: 178, tipo: 'jugador'},
    { equipo: 'Dinamarca', nombre: 'Escudo de Dinamarca', imgUrl: 'link', numero: 179, tipo: 'escudo'},
    { equipo: 'Dinamarca', nombre: 'CHISTENSEN', imgUrl: 'link', numero: 180, tipo: 'jugador'},
    { equipo: 'Dinamarca', nombre: 'KJAER', imgUrl: 'link', numero: 181, tipo: 'jugador'},
    { equipo: 'Dinamarca', nombre: 'MAEHLE', imgUrl: 'link', numero: 182, tipo: 'jugador'},
    { equipo: 'Dinamarca', nombre: 'VESTERGAARD', imgUrl: 'link', numero: 183, tipo: 'jugador'},
    { equipo: 'Dinamarca', nombre: 'DELANEY', imgUrl: 'link', numero: 184, tipo: 'jugador'},
    { equipo: 'Dinamarca', nombre: 'ERIKSEN', imgUrl: 'link', numero: 185, tipo: 'jugador'},
    { equipo: 'Dinamarca', nombre: 'HOJBJERG', imgUrl: 'link', numero: 186, tipo: 'jugador'},
    { equipo: 'Dinamarca', nombre: 'WASS', imgUrl: 'link', numero: 187, tipo: 'jugador'},
    { equipo: 'Dinamarca', nombre: 'BRAITHWAITE', imgUrl: 'link', numero: 188, tipo: 'jugador'},
    { equipo: 'Dinamarca', nombre: 'POULSEN', imgUrl: 'link', numero: 189, tipo: 'jugador'},
    { equipo: 'Túnez', nombre: 'Escudo de Túnez', imgUrl: 'link', numero: 190, tipo: 'escudo'},
    { equipo: 'Túnez', nombre: 'BEN SAID', imgUrl: 'link', numero: 191, tipo: 'jugador'},
    { equipo: 'Túnez', nombre: 'BRONN', imgUrl: 'link', numero: 193, tipo: 'jugador'},
    { equipo: 'Túnez', nombre: 'DRAGER', imgUrl: 'link', numero: 194, tipo: 'jugador'},
    { equipo: 'Túnez', nombre: 'MAALOUL', imgUrl: 'link', numero: 195, tipo: 'jugador'},
    { equipo: 'Túnez', nombre: 'TALBI', imgUrl: 'link', numero: 196, tipo: 'jugador'},
    { equipo: 'Túnez', nombre: 'KHAZRI', imgUrl: 'link', numero: 197, tipo: 'jugador'},
    { equipo: 'Túnez', nombre: 'LAIDOUNI', imgUrl: 'link', numero: 198, tipo: 'jugador'},
    { equipo: 'Túnez', nombre: 'SKHIRI', imgUrl: 'link', numero: 199, tipo: 'jugador'},
    { equipo: 'Túnez', nombre: 'SLIMANE', imgUrl: 'link', numero: 200, tipo: 'jugador'},
    { equipo: 'Túnez', nombre: 'JAZIRI', imgUrl: 'link', numero: 201, tipo: 'jugador'},
    { equipo: 'Túnez', nombre: 'MSAKNI', imgUrl: 'link', numero: 202, tipo: 'jugador'},
    { equipo: 'España', nombre: 'Escudo de España', imgUrl: 'link', numero: 203, tipo: 'escudo'},
    { equipo: 'España', nombre: 'SIMÓN', imgUrl: 'link', numero: 204, tipo: 'jugador'},
    { equipo: 'España', nombre: 'AZPILICUETA', imgUrl: 'link', numero: 205, tipo: 'jugador'},
    { equipo: 'España', nombre: 'GARCÍA', imgUrl: 'link', numero: 206, tipo: 'jugador'},
    { equipo: 'España', nombre: 'ALBA', imgUrl: 'link', numero: 207, tipo: 'jugador'},
    { equipo: 'España', nombre: 'LAPORTE', imgUrl: 'link', numero: 208, tipo: 'jugador'},
    { equipo: 'España', nombre: 'GAVI', imgUrl: 'link', numero: 209, tipo: 'jugador'},
    { equipo: 'España', nombre: 'PEDRI', imgUrl: 'link', numero: 210, tipo: 'jugador'},
    { equipo: 'España', nombre: 'BUSQUETS', imgUrl: 'link', numero: 211, tipo: 'jugador'},
    { equipo: 'España', nombre: 'OLMO', imgUrl: 'link', numero: 212, tipo: 'jugador'},
    { equipo: 'España', nombre: 'TORRES', imgUrl: 'link', numero: 213, tipo: 'jugador'},
    { equipo: 'España', nombre: 'MORATA', imgUrl: 'link', numero: 214, tipo: 'jugador'},
    { equipo: 'Costa Rica', nombre: 'Escudo de Costa Rica', imgUrl: 'link', numero: 215, tipo: 'escudo'},
    { equipo: 'Costa Rica', nombre: 'NAVAS', imgUrl: 'link', numero: 216, tipo: 'jugador'},
    { equipo: 'Costa Rica', nombre: 'CALVO', imgUrl: 'link', numero: 217, tipo: 'jugador'},
    { equipo: 'Costa Rica', nombre: 'DUARTE', imgUrl: 'link', numero: 218, tipo: 'jugador'},
    { equipo: 'Costa Rica', nombre: 'FULLER', imgUrl: 'link', numero: 219, tipo: 'jugador'},
    { equipo: 'Costa Rica', nombre: 'OVIEDO', imgUrl: 'link', numero: 220, tipo: 'jugador'},
    { equipo: 'Costa Rica', nombre: 'BORGES', imgUrl: 'link', numero: 221, tipo: 'jugador'},
    { equipo: 'Costa Rica', nombre: 'RUIZ', imgUrl: 'link', numero: 222, tipo: 'jugador'},
    { equipo: 'Costa Rica', nombre: 'TEJEDA', imgUrl: 'link', numero: 223, tipo: 'jugador'},
    { equipo: 'Costa Rica', nombre: 'BENNETTE', imgUrl: 'link', numero: 224, tipo: 'jugador'},
    { equipo: 'Costa Rica', nombre: 'CAMPBELL', imgUrl: 'link', numero: 225, tipo: 'jugador'},
    { equipo: 'Costa Rica', nombre: 'CONTRERAS', imgUrl: 'link', numero: 226, tipo: 'jugador'},
    { equipo: 'Alemania', nombre: 'Escudo de Alemania', imgUrl: 'link', numero: 227, tipo: 'escudo'},
    { equipo: 'Alemania', nombre: 'NEUER', imgUrl: 'link', numero: 228, tipo: 'jugador'},
    { equipo: 'Alemania', nombre: 'KEHRER', imgUrl: 'link', numero: 229, tipo: 'jugador'},
    { equipo: 'Alemania', nombre: 'RAUM', imgUrl: 'link', numero: 230, tipo: 'jugador'},
    { equipo: 'Alemania', nombre: 'RUDIGER', imgUrl: 'link', numero: 231, tipo: 'jugador'},
    { equipo: 'Alemania', nombre: 'SULE', imgUrl: 'link', numero: 232, tipo: 'jugador'},
    { equipo: 'Alemania', nombre: 'GORETZKA', imgUrl: 'link', numero: 233, tipo: 'jugador'},
    { equipo: 'Alemania', nombre: 'HAVERTZ', imgUrl: 'link', numero: 234, tipo: 'jugador'},
    { equipo: 'Alemania', nombre: 'KIMMICH', imgUrl: 'link', numero: 235, tipo: 'jugador'},
    { equipo: 'Alemania', nombre: 'GNABRY', imgUrl: 'link', numero: 236, tipo: 'jugador'},
    { equipo: 'Alemania', nombre: 'MULLER', imgUrl: 'link', numero: 237, tipo: 'jugador'},
    { equipo: 'Alemania', nombre: 'WERNER', imgUrl: 'link', numero: 238, tipo: 'jugador'},
    { equipo: 'Japón', nombre: 'Escudo de Japón', imgUrl: 'link', numero: 239, tipo: 'escudo'},
    { equipo: 'Japón', nombre: 'GONDA', imgUrl: 'link', numero: 240, tipo: 'jugador'},
    { equipo: 'Japón', nombre: 'NAGAMOTO', imgUrl: 'link', numero: 241, tipo: 'jugador'},
    { equipo: 'Japón', nombre: 'TOMIYASU', imgUrl: 'link', numero: 242, tipo: 'jugador'},
    { equipo: 'Japón', nombre: 'YAMANE', imgUrl: 'link', numero: 243, tipo: 'jugador'},
    { equipo: 'Japón', nombre: 'YOSHIDA', imgUrl: 'link', numero: 244, tipo: 'jugador'},
    { equipo: 'Japón', nombre: 'ENDO', imgUrl: 'link', numero: 245, tipo: 'jugador'},
    { equipo: 'Japón', nombre: 'SHIBASAKI', imgUrl: 'link', numero: 246, tipo: 'jugador'},
    { equipo: 'Japón', nombre: 'TANAKA', imgUrl: 'link', numero: 247, tipo: 'jugador'},
    { equipo: 'Japón', nombre: 'ITO', imgUrl: 'link', numero: 248, tipo: 'jugador'},
    { equipo: 'Japón', nombre: 'MINAMINO', imgUrl: 'link', numero: 249, tipo: 'jugador'},
    { equipo: 'Japón', nombre: 'OSAKO', imgUrl: 'link', numero: 250, tipo: 'jugador'},
    { equipo: 'Bélgica', nombre: 'Escudo de Bélgica', imgUrl: 'link', numero: 251, tipo: 'escudo'},
    { equipo: 'Bélgica', nombre: 'COURTOIS', imgUrl: 'link', numero: 252, tipo: 'jugador'},
    { equipo: 'Bélgica', nombre: 'ALDEWIRELD', imgUrl: 'link', numero: 253, tipo: 'jugador'},
    { equipo: 'Bélgica', nombre: 'DENAYER', imgUrl: 'link', numero: 254, tipo: 'jugador'},
    { equipo: 'Bélgica', nombre: 'MEUNIER', imgUrl: 'link', numero: 255, tipo: 'jugador'},
    { equipo: 'Bélgica', nombre: 'VERONGHEN', imgUrl: 'link', numero: 256, tipo: 'jugador'},
    { equipo: 'Bélgica', nombre: 'CARRASCO', imgUrl: 'link', numero: 257, tipo: 'jugador'},
    { equipo: 'Bélgica', nombre: 'BRUYNE', imgUrl: 'link', numero: 258, tipo: 'jugador'},
    { equipo: 'Bélgica', nombre: 'TIELEMANS', imgUrl: 'link', numero: 259, tipo: 'jugador'},
    { equipo: 'Bélgica', nombre: 'WITSEL', imgUrl: 'link', numero: 260, tipo: 'jugador'},
    { equipo: 'Bélgica', nombre: 'HAZARD', imgUrl: 'link', numero: 261, tipo: 'jugador'},
    { equipo: 'Bélgica', nombre: 'LUKAKU', imgUrl: 'link', numero: 262, tipo: 'jugador'},
    { equipo: 'Canada', nombre: 'Escudo de Canada', imgUrl: 'link', numero: 263, tipo: 'escudo'},
    { equipo: 'Canada', nombre: 'BORJAN', imgUrl: 'link', numero: 264, tipo: 'jugador'},
    { equipo: 'Canada', nombre: 'JOHNSTON', imgUrl: 'link', numero: 265, tipo: 'jugador'},
    { equipo: 'Canada', nombre: 'LARYEA', imgUrl: 'link', numero: 266, tipo: 'jugador'},
    { equipo: 'Canada', nombre: 'MILLER', imgUrl: 'link', numero: 267, tipo: 'jugador'},
    { equipo: 'Canada', nombre: 'VITÓRIA', imgUrl: 'link', numero: 268, tipo: 'jugador'},
    { equipo: 'Canada', nombre: 'BUCHANAN', imgUrl: 'link', numero: 269, tipo: 'jugador'},
    { equipo: 'Canada', nombre: 'DAVIES', imgUrl: 'link', numero: 270, tipo: 'jugador'},
    { equipo: 'Canada', nombre: 'EUSTÁQUIO', imgUrl: 'link', numero: 271, tipo: 'jugador'},
    { equipo: 'Canada', nombre: 'HUTCHINSON', imgUrl: 'link', numero: 272, tipo: 'jugador'},
    { equipo: 'Canada', nombre: 'DAVID', imgUrl: 'link', numero: 273, tipo: 'jugador'},
    { equipo: 'Canada', nombre: 'LARIN', imgUrl: 'link', numero: 274, tipo: 'jugador'},
    { equipo: 'Marruecos', nombre: 'Escudo de Marruecos', imgUrl: 'link', numero: 275, tipo: 'escudo'},
    { equipo: 'Marruecos', nombre: 'BOUNOU', imgUrl: 'link', numero: 276, tipo: 'jugador'},
    { equipo: 'Marruecos', nombre: 'AGUERD', imgUrl: 'link', numero: 277, tipo: 'jugador'},
    { equipo: 'Marruecos', nombre: 'HAKIMI', imgUrl: 'link', numero: 278, tipo: 'jugador'},
    { equipo: 'Marruecos', nombre: 'MASINA', imgUrl: 'link', numero: 279, tipo: 'jugador'},
    { equipo: 'Marruecos', nombre: 'SAISS', imgUrl: 'link', numero: 280, tipo: 'jugador'},
    { equipo: 'Marruecos', nombre: 'AMALLAH', imgUrl: 'link', numero: 281, tipo: 'jugador'},
    { equipo: 'Marruecos', nombre: 'AMRABAT', imgUrl: 'link', numero: 282, tipo: 'jugador'},
    { equipo: 'Marruecos', nombre: 'LOUZA', imgUrl: 'link', numero: 283, tipo: 'jugador'},
    { equipo: 'Marruecos', nombre: 'BOUFAL', imgUrl: 'link', numero: 284, tipo: 'jugador'},
    { equipo: 'Marruecos', nombre: 'NESYRI', imgUrl: 'link', numero: 285, tipo: 'jugador'},
    { equipo: 'Marruecos', nombre: 'MMAEE', imgUrl: 'link', numero: 286, tipo: 'jugador'},
    { equipo: 'Croacia', nombre: 'Escudo de Croacia', imgUrl: 'link', numero: 287, tipo: 'escudo'},
    { equipo: 'Croacia', nombre: 'LIVAKOVIC', imgUrl: 'link', numero: 288, tipo: 'jugador'},
    { equipo: 'Croacia', nombre: 'GVARDIOL', imgUrl: 'link', numero: 289, tipo: 'jugador'},
    { equipo: 'Croacia', nombre: 'JURANOVIC', imgUrl: 'link', numero: 290, tipo: 'jugador'},
    { equipo: 'Croacia', nombre: 'LOVREN', imgUrl: 'link', numero: 291, tipo: 'jugador'},
    { equipo: 'Croacia', nombre: 'SOSA', imgUrl: 'link', numero: 292, tipo: 'jugador'},
    { equipo: 'Croacia', nombre: 'BROZOVIC', imgUrl: 'link', numero: 293, tipo: 'jugador'},
    { equipo: 'Croacia', nombre: 'KOVACIC', imgUrl: 'link', numero: 294, tipo: 'jugador'},
    { equipo: 'Croacia', nombre: 'MODRIC', imgUrl: 'link', numero: 295, tipo: 'jugador'},
    { equipo: 'Croacia', nombre: 'PERISIC', imgUrl: 'link', numero: 296, tipo: 'jugador'},
    { equipo: 'Croacia', nombre: 'VLASIC', imgUrl: 'link', numero: 297, tipo: 'jugador'},
    { equipo: 'Croacia', nombre: 'KRAMRIC', imgUrl: 'link', numero: 298, tipo: 'jugador'},
    { equipo: 'Brasil', nombre: 'Escudo de Brasil', imgUrl: 'link', numero: 299, tipo: 'escudo'},
    { equipo: 'Brasil', nombre: 'ALLISON', imgUrl: 'link', numero: 300, tipo: 'jugador'},
    { equipo: 'Brasil', nombre: 'SANDRO', imgUrl: 'link', numero: 301, tipo: 'jugador'},
    { equipo: 'Brasil', nombre: 'DANILO', imgUrl: 'link', numero: 302, tipo: 'jugador'},
    { equipo: 'Brasil', nombre: 'MARQUINHOS', imgUrl: 'link', numero: 303, tipo: 'jugador'},
    { equipo: 'Brasil', nombre: 'SILVA', imgUrl: 'link', numero: 304, tipo: 'jugador'},
    { equipo: 'Brasil', nombre: 'CASEMIRO', imgUrl: 'link', numero: 305, tipo: 'jugador'},
    { equipo: 'Brasil', nombre: 'FRED', imgUrl: 'link', numero: 306, tipo: 'jugador'},
    { equipo: 'Brasil', nombre: 'PAQUETÁ', imgUrl: 'link', numero: 307, tipo: 'jugador'},
    { equipo: 'Brasil', nombre: 'GABRIEL JESUS', imgUrl: 'link', numero: 308, tipo: 'jugador'},
    { equipo: 'Brasil', nombre: 'NEYMAR JR', imgUrl: 'link', numero: 309, tipo: 'jugador'},
    { equipo: 'Brasil', nombre: 'VINICIUS JR', imgUrl: 'link', numero: 310, tipo: 'jugador'},
    { equipo: 'Serbia', nombre: 'Escudo de Serbia', imgUrl: 'link', numero: 311, tipo: 'escudo'},
    { equipo: 'Serbia', nombre: 'RAJKOVIC', imgUrl: 'link', numero: 312, tipo: 'jugador'},
    { equipo: 'Serbia', nombre: 'MILENKOVIC', imgUrl: 'link', numero: 313, tipo: 'jugador'},
    { equipo: 'Serbia', nombre: 'PAVLOVIC', imgUrl: 'link', numero: 314, tipo: 'jugador'},
    { equipo: 'Serbia', nombre: 'VELJKOVIC', imgUrl: 'link', numero: 315, tipo: 'jugador'},
    { equipo: 'Serbia', nombre: 'GUDELJ', imgUrl: 'link', numero: 316, tipo: 'jugador'},
    { equipo: 'Serbia', nombre: 'KOSTIC', imgUrl: 'link', numero: 317, tipo: 'jugador'},
    { equipo: 'Serbia', nombre: 'LAZOVIC', imgUrl: 'link', numero: 318, tipo: 'jugador'},
    { equipo: 'Serbia', nombre: 'SAVIC', imgUrl: 'link', numero: 319, tipo: 'jugador'},
    { equipo: 'Serbia', nombre: 'MITROVIC', imgUrl: 'link', numero: 320, tipo: 'jugador'},
    { equipo: 'Serbia', nombre: 'TADIC', imgUrl: 'link', numero: 321, tipo: 'jugador'},
    { equipo: 'Serbia', nombre: 'VLAHOVIC', imgUrl: 'link', numero: 322, tipo: 'jugador'},
    { equipo: 'Suiza', nombre: 'Escudo de Suiza', imgUrl: 'link', numero: 323, tipo: 'escudo'},
    { equipo: 'Suiza', nombre: 'SOMMER', imgUrl: 'link', numero: 324, tipo: 'jugador'},
    { equipo: 'Suiza', nombre: 'AKANJI', imgUrl: 'link', numero: 325, tipo: 'jugador'},
    { equipo: 'Suiza', nombre: 'ELVEDI', imgUrl: 'link', numero: 326, tipo: 'jugador'},
    { equipo: 'Suiza', nombre: 'RODRIGUEZ', imgUrl: 'link', numero: 327, tipo: 'jugador'},
    { equipo: 'Suiza', nombre: 'WIDMER', imgUrl: 'link', numero: 328, tipo: 'jugador'},
    { equipo: 'Suiza', nombre: 'FREULER', imgUrl: 'link', numero: 329, tipo: 'jugador'},
    { equipo: 'Suiza', nombre: 'SHAQIRI', imgUrl: 'link', numero: 330, tipo: 'jugador'},
    { equipo: 'Suiza', nombre: 'XHAKA', imgUrl: 'link', numero: 331, tipo: 'jugador'},
    { equipo: 'Suiza', nombre: 'ZAKARIA', imgUrl: 'link', numero: 332, tipo: 'jugador'},
    { equipo: 'Suiza', nombre: 'EMBOLO', imgUrl: 'link', numero: 333, tipo: 'jugador'},
    { equipo: 'Suiza', nombre: 'SEFEROVIC', imgUrl: 'link', numero: 334, tipo: 'jugador'},
    { equipo: 'Camerún', nombre: 'Escudo de Camerún', imgUrl: 'link', numero: 335, tipo: 'escudo'},
    { equipo: 'Camerún', nombre: 'ONAMA', imgUrl: 'link', numero: 336, tipo: 'jugador'},
    { equipo: 'Camerún', nombre: 'CASTELLETO', imgUrl: 'link', numero: 337, tipo: 'jugador'},
    { equipo: 'Camerún', nombre: 'FAI', imgUrl: 'link', numero: 338, tipo: 'jugador'},
    { equipo: 'Camerún', nombre: 'NGADEU', imgUrl: 'link', numero: 339, tipo: 'jugador'},
    { equipo: 'Camerún', nombre: 'NOUHOU', imgUrl: 'link', numero: 340, tipo: 'jugador'},
    { equipo: 'Camerún', nombre: 'GOUET', imgUrl: 'link', numero: 341, tipo: 'jugador'},
    { equipo: 'Camerún', nombre: 'ANGUISSA', imgUrl: 'link', numero: 342, tipo: 'jugador'},
    { equipo: 'Camerún', nombre: 'ABOUDAKAR', imgUrl: 'link', numero: 343, tipo: 'jugador'},
    { equipo: 'Camerún', nombre: 'CHOUPO-MOTING', imgUrl: 'link', numero: 344, tipo: 'jugador'},
    { equipo: 'Camerún', nombre: 'NGAMALEU', imgUrl: 'link', numero: 345, tipo: 'jugador'},
    { equipo: 'Camerún', nombre: 'EKAMBI', imgUrl: 'link', numero: 346, tipo: 'jugador'},
    { equipo: 'Portugal', nombre: 'Escudo de Portugal', imgUrl: 'link', numero: 347, tipo: 'escudo'},
    { equipo: 'Portugal', nombre: 'COSTA', imgUrl: 'link', numero: 348, tipo: 'jugador'},
    { equipo: 'Portugal', nombre: 'CANCELO', imgUrl: 'link', numero: 349, tipo: 'jugador'},
    { equipo: 'Portugal', nombre: 'PEPE', imgUrl: 'link', numero: 350, tipo: 'jugador'},
    { equipo: 'Portugal', nombre: 'GUERREIRO', imgUrl: 'link', numero: 351, tipo: 'jugador'},
    { equipo: 'Portugal', nombre: 'DIAS', imgUrl: 'link', numero: 352, tipo: 'jugador'},
    { equipo: 'Portugal', nombre: 'SILVA', imgUrl: 'link', numero: 353, tipo: 'jugador'},
    { equipo: 'Portugal', nombre: 'FERNANDES', imgUrl: 'link', numero: 354, tipo: 'jugador'},
    { equipo: 'Portugal', nombre: 'PEREIRA', imgUrl: 'link', numero: 355, tipo: 'jugador'},
    { equipo: 'Portugal', nombre: 'MOUTINHO', imgUrl: 'link', numero: 356, tipo: 'jugador'},
    { equipo: 'Portugal', nombre: 'CRISTIANO RONALDO', imgUrl: 'link', numero: 357, tipo: 'jugador'},
    { equipo: 'Portugal', nombre: 'JOTA', imgUrl: 'link', numero: 358, tipo: 'jugador'},
    { equipo: 'Ghana', nombre: 'Escudo de Ghana', imgUrl: 'link', numero: 359, tipo: 'escudo'},
    { equipo: 'Ghana', nombre: 'WOLLACOTT', imgUrl: 'link', numero: 360, tipo: 'jugador'},
    { equipo: 'Ghana', nombre: 'AMARTEY', imgUrl: 'link', numero: 361, tipo: 'jugador'},
    { equipo: 'Ghana', nombre: 'BABA', imgUrl: 'link', numero: 362, tipo: 'jugador'},
    { equipo: 'Ghana', nombre: 'DJIKU', imgUrl: 'link', numero: 363, tipo: 'jugador'},
    { equipo: 'Ghana', nombre: 'YIADOM', imgUrl: 'link', numero: 364, tipo: 'jugador'},
    { equipo: 'Ghana', nombre: 'IDDRISU BABA', imgUrl: 'link', numero: 365, tipo: 'jugador'},
    { equipo: 'Ghana', nombre: 'KUDUS', imgUrl: 'link', numero: 366, tipo: 'jugador'},
    { equipo: 'Ghana', nombre: 'PARTEY', imgUrl: 'link', numero: 367, tipo: 'jugador'},
    { equipo: 'Ghana', nombre: 'AYEW', imgUrl: 'link', numero: 368, tipo: 'jugador'},
    { equipo: 'Ghana', nombre: 'JORDAN AYEW', imgUrl: 'link', numero: 369, tipo: 'jugador'},
    { equipo: 'Ghana', nombre: 'SULEMANA', imgUrl: 'link', numero: 370, tipo: 'jugador'},
    { equipo: 'Uruguay', nombre: 'Escudo de Uruguay', imgUrl: 'link', numero: 371, tipo: 'escudo'},
    { equipo: 'Uruguay', nombre: 'MUSLERA', imgUrl: 'link', numero: 372, tipo: 'jugador'},
    { equipo: 'Uruguay', nombre: 'ARAUJO', imgUrl: 'link', numero: 373, tipo: 'jugador'},
    { equipo: 'Uruguay', nombre: 'GIMENEZ', imgUrl: 'link', numero: 374, tipo: 'jugador'},
    { equipo: 'Uruguay', nombre: 'GODIN', imgUrl: 'link', numero: 375, tipo: 'jugador'},
    { equipo: 'Uruguay', nombre: 'OLIVERA', imgUrl: 'link', numero: 376, tipo: 'jugador'},
    { equipo: 'Uruguay', nombre: 'BETANCUR', imgUrl: 'link', numero: 377, tipo: 'jugador'},
    { equipo: 'Uruguay', nombre: 'ARRASCAETA', imgUrl: 'link', numero: 378, tipo: 'jugador'},
    { equipo: 'Uruguay', nombre: 'DE LA CRUZ', imgUrl: 'link', numero: 379, tipo: 'jugador'},
    { equipo: 'Uruguay', nombre: 'VALVERDE', imgUrl: 'link', numero: 380, tipo: 'jugador'},
    { equipo: 'Uruguay', nombre: 'CAVANI', imgUrl: 'link', numero: 381, tipo: 'jugador'},
    { equipo: 'Uruguay', nombre: 'SUÁREZ', imgUrl: 'link', numero: 382, tipo: 'jugador'},
    { equipo: 'Republica de Korea', nombre: 'Escudo de Republica de Korea', imgUrl: 'link', numero: 383, tipo: 'escudo'},
    { equipo: 'Republica de Korea', nombre: 'KIM', imgUrl: 'link', numero: 384, tipo: 'jugador'},
    { equipo: 'Republica de Korea', nombre: 'JAE KIM', imgUrl: 'link', numero: 385, tipo: 'jugador'},
    { equipo: 'Republica de Korea', nombre: 'GWON KIM', imgUrl: 'link', numero: 386, tipo: 'jugador'},
    { equipo: 'Republica de Korea', nombre: 'SU KIM', imgUrl: 'link', numero: 387, tipo: 'jugador'},
    { equipo: 'Republica de Korea', nombre: 'LEE', imgUrl: 'link', numero: 388, tipo: 'jugador'},
    { equipo: 'Republica de Korea', nombre: 'HWANG', imgUrl: 'link', numero: 389, tipo: 'jugador'},
    { equipo: 'Republica de Korea', nombre: 'JUNG', imgUrl: 'link', numero: 390, tipo: 'jugador'},
    { equipo: 'Republica de Korea', nombre: 'SUNG LEE', imgUrl: 'link', numero: 391, tipo: 'jugador'},
    { equipo: 'Republica de Korea', nombre: 'CHAN HWANG', imgUrl: 'link', numero: 392, tipo: 'jugador'},
    { equipo: 'Republica de Korea', nombre: 'JO HWANG', imgUrl: 'link', numero: 393, tipo: 'jugador'},
    { equipo: 'Republica de Korea', nombre: 'HEUNG MIN SON', imgUrl: 'link', numero: 394, tipo: 'jugador'},
])

db.users.find({_id:ObjectId("6374c78f8ae980334a7c3197")}) Anuel 
db.laminas.insertMany([
    {ownerId:"6374c78f8ae980334a7c3197" ,numero: 10 , cantidad:2},
    {ownerId:"6374c78f8ae980334a7c3197" ,numero: 11 , cantidad:1},
    {ownerId:"6374c78f8ae980334a7c3197" ,numero: 13 , cantidad:6},
    {ownerId:"6374c78f8ae980334a7c3197" ,numero: 15 , cantidad:6},
])

*/